<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.14.0" />
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.2" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.10.0" />
    <PackageReference Include="MimeKit" Version="4.12.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Roy.Logging\Roy.Logging.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Avalon.Base.Extension">
      <HintPath>..\..\libraries\Avalon\Avalon.Base.Extension.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore">
      <HintPath>libs\Microsoft.AspNetCore.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore.Diagnostics">
      <HintPath>libs\Microsoft.AspNetCore.Diagnostics.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore.Diagnostics.Abstractions">
      <HintPath>libs\Microsoft.AspNetCore.Diagnostics.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore.Hosting.Abstractions">
      <HintPath>libs\Microsoft.AspNetCore.Hosting.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore.Http">
      <HintPath>libs\Microsoft.AspNetCore.Http.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore.Http.Abstractions">
      <HintPath>libs\Microsoft.AspNetCore.Http.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore.Http.Features">
      <HintPath>libs\Microsoft.AspNetCore.Http.Features.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore.Routing">
      <HintPath>libs\Microsoft.AspNetCore.Routing.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Configuration.Binder">
      <HintPath>libs\Microsoft.Extensions.Configuration.Binder.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Features">
      <HintPath>libs\Microsoft.Extensions.Features.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Hosting.Abstractions">
      <HintPath>libs\Microsoft.Extensions.Hosting.Abstractions.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
