//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roy.Logging.Resources.Languages.EmailTemplate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailLabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Roy.Logging.Resources.Languages.EmailTemplate.EmailLabels", typeof(EmailLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly Name:.
        /// </summary>
        public static string ApplicationFriendlyName {
            get {
                return ResourceManager.GetString("ApplicationFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLICATION INFORMATION.
        /// </summary>
        public static string ApplicationInformationHeader {
            get {
                return ResourceManager.GetString("ApplicationInformationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugging Enabled:.
        /// </summary>
        public static string ApplicationIsDebuggingEnabled {
            get {
                return ResourceManager.GetString("ApplicationIsDebuggingEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fully Trusted:.
        /// </summary>
        public static string ApplicationIsFullyTrusted {
            get {
                return ResourceManager.GetString("ApplicationIsFullyTrusted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Path:.
        /// </summary>
        public static string ApplicationPhysicalApplicationPath {
            get {
                return ResourceManager.GetString("ApplicationPhysicalApplicationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Domain Name:.
        /// </summary>
        public static string ApplicationUserDomainName {
            get {
                return ResourceManager.GetString("ApplicationUserDomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application User Name:.
        /// </summary>
        public static string ApplicationUserName {
            get {
                return ResourceManager.GetString("ApplicationUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Location:.
        /// </summary>
        public static string AssemblyLocationTag {
            get {
                return ResourceManager.GetString("AssemblyLocationTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET CLR Version:.
        /// </summary>
        public static string CLRVersion {
            get {
                return ResourceManager.GetString("CLRVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom List of Parameters in JSON Format:.
        /// </summary>
        public static string CustomListOfParametersJSON {
            get {
                return ResourceManager.GetString("CustomListOfParametersJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Message:.
        /// </summary>
        public static string CustomMessage {
            get {
                return ResourceManager.GetString("CustomMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Name:.
        /// </summary>
        public static string DomainName {
            get {
                return ResourceManager.GetString("DomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Id:.
        /// </summary>
        public static string ErrorId {
            get {
                return ResourceManager.GetString("ErrorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXCEPTION INFORMATION.
        /// </summary>
        public static string ExceptionInformationHeader {
            get {
                return ResourceManager.GetString("ExceptionInformationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Message:.
        /// </summary>
        public static string ExceptionMessageTag {
            get {
                return ResourceManager.GetString("ExceptionMessageTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roy Exception - Issue Level: *|Level|* - Id: *|IssueId|*.
        /// </summary>
        public static string ExceptionSubject {
            get {
                return ResourceManager.GetString("ExceptionSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Load.
        /// </summary>
        public static string FailedToLoad {
            get {
                return ResourceManager.GetString("FailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Exception in JSON Format:.
        /// </summary>
        public static string FullExceptionInJSONFormat {
            get {
                return ResourceManager.GetString("FullExceptionInJSONFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Issue in JSON Format:.
        /// </summary>
        public static string FullIssueInJSONFormat {
            get {
                return ResourceManager.GetString("FullIssueInJSONFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Link:.
        /// </summary>
        public static string HelpLinkTag {
            get {
                return ResourceManager.GetString("HelpLinkTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string IssueDate {
            get {
                return ResourceManager.GetString("IssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Level:.
        /// </summary>
        public static string IssueLevel {
            get {
                return ResourceManager.GetString("IssueLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Id:.
        /// </summary>
        public static string LogId {
            get {
                return ResourceManager.GetString("LogId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG INFORMATION.
        /// </summary>
        public static string LogInformationHeader {
            get {
                return ResourceManager.GetString("LogInformationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Caller File Name:.
        /// </summary>
        public static string MethodCallerFileName {
            get {
                return ResourceManager.GetString("MethodCallerFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Caller Line Number:.
        /// </summary>
        public static string MethodCallerLineNumber {
            get {
                return ResourceManager.GetString("MethodCallerLineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Caller Method Name:.
        /// </summary>
        public static string MethodCallerMethodName {
            get {
                return ResourceManager.GetString("MethodCallerMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Information.
        /// </summary>
        public static string MethodInformationHeader {
            get {
                return ResourceManager.GetString("MethodInformationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Parameters:.
        /// </summary>
        public static string MethodParameters {
            get {
                return ResourceManager.GetString("MethodParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operative System:.
        /// </summary>
        public static string OperativeSystem {
            get {
                return ResourceManager.GetString("OperativeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operative System Version:.
        /// </summary>
        public static string OperativeSystemVersion {
            get {
                return ResourceManager.GetString("OperativeSystemVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roy Logging - Issue Level: *|Level|* - Id: *|IssueId|*.
        /// </summary>
        public static string RoyLoginSubject {
            get {
                return ResourceManager.GetString("RoyLoginSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVER/COMPUTER INFORMATION.
        /// </summary>
        public static string ServerInformationHeader {
            get {
                return ResourceManager.GetString("ServerInformationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server/Computer Name:.
        /// </summary>
        public static string ServerName {
            get {
                return ResourceManager.GetString("ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source:.
        /// </summary>
        public static string SourceTag {
            get {
                return ResourceManager.GetString("SourceTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Frame in JSON Format:.
        /// </summary>
        public static string StackFrameInJSONFormat {
            get {
                return ResourceManager.GetString("StackFrameInJSONFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Trace:.
        /// </summary>
        public static string StackTraceTag {
            get {
                return ResourceManager.GetString("StackTraceTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Account Name:.
        /// </summary>
        public static string UserAccountName {
            get {
                return ResourceManager.GetString("UserAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Logged in JSON Format:.
        /// </summary>
        public static string ValueLoggedInJSONFormat {
            get {
                return ResourceManager.GetString("ValueLoggedInJSONFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookies Values:.
        /// </summary>
        public static string WebApplicationCookiesValues {
            get {
                return ResourceManager.GetString("WebApplicationCookiesValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current URL:.
        /// </summary>
        public static string WebApplicationCurrentURL {
            get {
                return ResourceManager.GetString("WebApplicationCurrentURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current URL Parameters:.
        /// </summary>
        public static string WebApplicationCurrentURLParameters {
            get {
                return ResourceManager.GetString("WebApplicationCurrentURLParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers Values:.
        /// </summary>
        public static string WebApplicationHeadersValues {
            get {
                return ResourceManager.GetString("WebApplicationHeadersValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Connection:.
        /// </summary>
        public static string WebApplicationIsSecureConnection {
            get {
                return ResourceManager.GetString("WebApplicationIsSecureConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous URL:.
        /// </summary>
        public static string WebApplicationPreviousURL {
            get {
                return ResourceManager.GetString("WebApplicationPreviousURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Domain:.
        /// </summary>
        public static string WebApplicationUserDomainName {
            get {
                return ResourceManager.GetString("WebApplicationUserDomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User IP:.
        /// </summary>
        public static string WebApplicationUserHostIP {
            get {
                return ResourceManager.GetString("WebApplicationUserHostIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Preferred Language:.
        /// </summary>
        public static string WebApplicationUserLanguagePreferences {
            get {
                return ResourceManager.GetString("WebApplicationUserLanguagePreferences", resourceCulture);
            }
        }
    }
}
