//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roy.Logging.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RoyValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RoyValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Roy.Logging.Resources.RoyValues", typeof(RoyValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;body leftmargin=&quot;0&quot; marginwidth=&quot;0&quot; topmargin=&quot;0&quot; marginheight=&quot;0&quot; offset=&quot;0&quot;
        ///        style=&quot;background:none repeat scroll 0 0 #FFFFFF; width:100%; height:100%&quot; width=&quot;100%&quot; align=&quot;center&quot;&gt;
        ///        &lt;table width=&quot;100%&quot; height=&quot;100%&quot; bgcolor=&quot;#FFFFFF&quot; cellpadding=&quot;10&quot; cellspacing=&quot;0&quot;&gt;
        ///            &lt;tr valign=&quot;top&quot; align=&quot;center&quot;&gt;
        ///                &lt;td  height=&quot;100%&quot; style=&quot;height:100%;&quot;&gt;
        ///                    &lt;table width=&quot;500px&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; bgcolor=&quot;#FFFFFF&quot;&gt;
        ///                [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ExceptionHTMLBody {
            get {
                return ResourceManager.GetString("ExceptionHTMLBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;body leftmargin=&quot;0&quot; marginwidth=&quot;0&quot; topmargin=&quot;0&quot; marginheight=&quot;0&quot; offset=&quot;0&quot;
        ///        style=&quot;background:none repeat scroll 0 0 #FFFFFF; width:100%; height:100%&quot; width=&quot;100%&quot; align=&quot;center&quot;&gt;
        ///        &lt;table width=&quot;100%&quot; height=&quot;100%&quot; bgcolor=&quot;#FFFFFF&quot; cellpadding=&quot;10&quot; cellspacing=&quot;0&quot;&gt;
        ///            &lt;tr valign=&quot;top&quot; align=&quot;center&quot;&gt;
        ///                &lt;td  height=&quot;100%&quot; style=&quot;height:100%;&quot;&gt;
        ///                    &lt;table width=&quot;500px&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; bgcolor=&quot;#FFFFFF&quot;&gt;
        ///                [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LogHTMLBody {
            get {
                return ResourceManager.GetString("LogHTMLBody", resourceCulture);
            }
        }
    }
}
